[package]
name = "arcropolis"
version = "0.4.0"
authors = ["Raytwo <raytwost@gmail.com>, jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.7.3"
toml = "0.5.6"
lazy_static = "1.4"
owo-colors = "1.0.3"
serde = { version = "1", features = ["derive"] }
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }


[patch.crates-io]
getrandom = { git = "https://github.com/Raytwo/getrandom" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
